name: Update epoch
on:
  schedule:
    - cron: '0 1/2 * * *'
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: main
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
      
      - name: Install
        run: yarn

      - name: Generate epoch data
        env:
          NODE_URL: ${{ secrets.NODE_URL }}
        run: yarn generateEpochData

      - name: Build
        run: yarn build

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Updating to epoch ${{ env.EPOCH }}